import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Home from "./home";

const inter = Inter({ subsets: ["latin"] });

export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      {/* <h1 className="text-center h-screen bg-primary">Food Ordering</h1> */}
   
    </>
  );
}
