import React, { useState } from "react";
import Image from "next/image";
import Title from "../../components/layout/ui/Title";
import Head from "next/head";
import { FaShoppingCart } from "react-icons/fa";
import { addProduct } from "../../redux/cardSlice";
import { useDispatch, useSelector } from "react-redux";

const itemsExtra = [
  {
    id: 1,
    name: "Ketchup",
    price: 1,
  },
  {
    id: 2,
    name: "Mayonnaise",
    price: 1,
  },
  {
    id: 3,
    name: "Ranch Sauce",
    price: 2,
  },
];

const Products = () => {
  const [prices, setPrices] = useState([10, 20, 30]);
  const [price, setPrice] = useState(prices[0]);
  const [size, setSize] = useState(0);
  const [extraItems, setExtraItems] = useState(itemsExtra);
  const [extras, setExtras] = useState([]);
  const card = useSelector((state) => state.card);
  const dispatch = useDispatch();
  const foodItems = [
    {
      id: 1,
      name: "Pizza 1",
      price: 10,
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem ea repellat, velit in impedit, facilis, molestias fugiat pariatur amet magni officia dolor iste laudantium assumenda ab inventore earum asperiores aspernatur.",
      extraOptions: [{ id: 1, name: "Mayonnaise", price: 1 }],
    },
  ];
  const handleSize = (sizeIndex) => {
    const difference = prices[sizeIndex] - prices[size];
    setSize(sizeIndex);
    changePrice(difference);
  };

  const changePrice = (number) => {
    setPrice(price + number);
  };

  const handleChange = (e, val) => {

    const checked = e.target.checked;
    if (checked) {
      setExtras([...extras, val]);
      changePrice(val.price);
    } else {
      setExtras(extras.filter(item => item !== val));
      changePrice(-val.price);
    }
   

  };
  console.log(extras)
  const handleClick = () => {
    dispatch(addProduct({ ...foodItems[0], extras, price, quantity: 1 }));
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&display=swap"
          rel="stylesheet"
        />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="py-40 flex  pt-24 items-center justify-center gap-x-20 flex-col md:flex-row">
        <div className="md:ml-10">
          <div className="relative lg:w-[400px] lg:h-[400px] md:w-[300px] md:h-[300px] w-[200px] h-[200px] lg:mx-16 ">
            <Image src="/images/f1.png" alt="" layout="fill" />
          </div>
        </div>

        <div className="flex flex-col">
          <Title addClass="text-4xl text-center md:text-start">
            Good Pizza
          </Title>
          <span className="text-primary text-2xl font-bold underline underline-offset-2 inline-block my-2 text-center md:text-start">
            ${price}
          </span>
          <p className="text-sm my-4 mx-5 text-center md:text-start md:mx-0">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem ea
            repellat, velit in impedit, facilis, molestias fugiat pariatur amet
            magni officia dolor iste laudantium assumenda ab inventore earum
            asperiores aspernatur.
          </p>
          <h4 className="font-bold text-center md:text-start">
            Choose The Size
          </h4>
          <div className="flex items-center gap-20 justify-center md:justify-start my-3">
            <div
              className="relative w-12 h-12 cursor-pointer"
              onClick={() => handleSize(0)}
            >
              <Image src="/images/size.png" alt="" layout="fill" />
              <span className="absolute top-0 -right-7 text-sm rounded-lg bg-primary px-1">
                Small
              </span>
            </div>
            <div
              className="relative w-16 h-16 cursor-pointer"
              onClick={() => handleSize(1)}
            >
              <Image src="/images/size.png" alt="" layout="fill" />
              <span className="absolute top-0 -right-9 text-sm rounded-lg bg-primary px-1">
                Medium
              </span>
            </div>
            <div
              className="relative w-20 h-20 cursor-pointer"
              onClick={() => handleSize(2)}
            >
              <Image src="/images/size.png" alt="" layout="fill" />
              <span className="absolute top-0 -right-4 rounded-lg bg-primary px-1 text-sm">
                Large
              </span>
            </div>
          </div>
          <h4 className="my-2 font-bold text-center md:text-start">
            Choose Additional Ingredients
          </h4>

          <div className="flex gap-x-4 md:justify-start justify-center">
            {extraItems.map((val) => (
              <label className="flex items-center" key={val.id}>
                <input
                  type="checkbox"
                  onChange={(e) => handleChange(e, val)}
                  className="w-5 h-5 accent-primary"
                />
                <span className="text-sm font-semibold px-1">{val.name}</span>
              </label>
            ))}
          </div>
          <div className="flex md:justify-start justify-center">
            <button
              className="btn-primary mt-5 flex items-center gap-x-2 w-44"
              onClick={handleClick}
            >
              Add to Cart
              <span>
                <FaShoppingCart />
              </span>
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Products;
